version: '3.8'

services:

  db:
    image: mariadb
    container_name: db_smd
    restart: always
    environment:
      MYSQL_DATABASE: "db_smd"
      MYSQL_CHARSET: "utf8mb4"
      MYSQL_ROOT_PASSWORD: "smd"
    volumes:
      - db-data:/var/lib/mariadb
    ports:
      - "3306:3306"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmni_smd
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_smd
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - dev

  www:
    build: docker
    container_name: www_smb_project
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

volumes:
  db-data:

networks:
  dev:   
